name: Protobuf Distribution (Token)

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  setup-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: Setup Version
        id: version
        run: |
          YEAR=$(date +%y)
          MONTH=$(date +%m)
          BUILD_NUMBER=${{ github.run_number }}
          echo "version=$YEAR.$MONTH.$BUILD_NUMBER" >> $GITHUB_OUTPUT
          echo "Generated version: $YEAR.$MONTH.$BUILD_NUMBER"

  python-domain:
    runs-on: ubuntu-latest
    needs: setup-version
    steps:
      - name: Checkout system contracts
        uses: actions/checkout@v4
        with:
          path: eapp-system-contracts

      - name: Checkout Python Domain
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/eapp-python-domain
          token: ${{ secrets.PROTOBUF_TOKEN || secrets.GITHUB_TOKEN }}
          path: eapp-python-domain

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install protobuf==4.25.1
          pip install grpcio-tools==1.60.0
          pip install grpcio==1.60.0
          pip install twine

      - name: Generate Python protobuf code
        run: |
          EAPP_PROTO_SRC_DIR="${{ github.workspace }}/eapp-system-contracts/src/main/proto"
          EAPP_PROTO_PYTHON_OUT_DIR="${{ github.workspace }}/eapp-python-domain/src/eapp_python_domain"
          
          echo "Source directory: $EAPP_PROTO_SRC_DIR"
          echo "Output directory: $EAPP_PROTO_PYTHON_OUT_DIR"
          
          mkdir -p "$EAPP_PROTO_PYTHON_OUT_DIR"
          
          find "$EAPP_PROTO_SRC_DIR" -name "*.proto" | head -20 | while read proto_file; do
            echo "Processing: $proto_file"
            python -m grpc_tools.protoc \
              --python_out="$EAPP_PROTO_PYTHON_OUT_DIR" \
              --grpc_python_out="$EAPP_PROTO_PYTHON_OUT_DIR" \
              --pyi_out="$EAPP_PROTO_PYTHON_OUT_DIR" \
              -I "$EAPP_PROTO_SRC_DIR" \
              "$proto_file"
          done
          
          echo "Generated files:"
          find "$EAPP_PROTO_PYTHON_OUT_DIR" -name "*.py" | head -10

      - name: Create __init__.py files
        run: |
          EAPP_PROTO_PYTHON_OUT_DIR="${{ github.workspace }}/eapp-python-domain/src/eapp_python_domain"
          find "$EAPP_PROTO_PYTHON_OUT_DIR" -type d -exec touch {}/__init__.py \;

      - name: Update Python package version
        run: |
          cd ${{ github.workspace }}/eapp-python-domain
          if [ -f "setup.py" ]; then
            sed -i "s/version='[^']*'/version='${{ needs.setup-version.outputs.version }}'/" setup.py
          else
            echo "Creating setup.py..."
            echo 'from setuptools import setup, find_packages' > setup.py
            echo '' >> setup.py
            echo 'setup(' >> setup.py
            echo '    name="eapp-python-domain",' >> setup.py
            echo '    version="${{ needs.setup-version.outputs.version }}",' >> setup.py
            echo '    description="Generated protobuf code for EthosVerse Python domain",' >> setup.py
            echo '    packages=find_packages(where="src"),' >> setup.py
            echo '    package_dir={"": "src"},' >> setup.py
            echo '    python_requires=">=3.7",' >> setup.py
            echo '    install_requires=[' >> setup.py
            echo '        "protobuf>=3.20.0",' >> setup.py
            echo '        "grpcio>=1.50.0",' >> setup.py
            echo '    ],' >> setup.py
            echo ')' >> setup.py
          fi

      - name: Build Python package
        run: |
          cd ${{ github.workspace }}/eapp-python-domain
          python setup.py sdist

      - name: Publish Python package to GitHub Packages
        if: github.ref == 'refs/heads/master'
        run: |
          cd ${{ github.workspace }}/eapp-python-domain
          
          echo '[distutils]' > ~/.pypirc
          echo 'index-servers = github' >> ~/.pypirc
          echo '' >> ~/.pypirc
          echo '[github]' >> ~/.pypirc
          echo 'repository = https://github.com/${{ github.repository_owner }}/eapp-python-domain/packages/pypi' >> ~/.pypirc
          echo 'username = ${{ github.actor }}' >> ~/.pypirc
          echo 'password = ${{ secrets.PROTOBUF_TOKEN || secrets.GITHUB_TOKEN }}' >> ~/.pypirc
          
          twine upload -r github dist/*

      - name: Commit and push Python changes
        run: |
          cd ${{ github.workspace }}/eapp-python-domain
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Update protobuf generated code - version ${{ needs.setup-version.outputs.version }}" || echo "No changes to commit"
          git push origin master || echo "No changes to push"

  notify-completion:
    runs-on: ubuntu-latest
    needs: [python-domain]
    if: always()
    steps:
      - name: Notify completion
        run: |
          echo "Protobuf distribution with token completed!"
          echo "Version: ${{ needs.setup-version.outputs.version }}"
          echo "Check individual job logs for details." 