name: Test Package Upload

on:
  workflow_dispatch:

jobs:
  test-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Python Domain
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/eapp-python-domain
          token: ${{ secrets.PROTOBUF_TOKEN || secrets.GITHUB_TOKEN }}
          path: eapp-python-domain

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install twine setuptools wheel

      - name: Create test package
        run: |
          cd eapp-python-domain
          echo 'from setuptools import setup' > setup.py
          echo 'setup(name="test-package", version="0.1.0")' >> setup.py
          python setup.py sdist

      - name: Create package via GitHub API
        run: |
          echo "Creating package via GitHub API..."
          curl -X POST \
            -H "Authorization: token ${{ secrets.PROTOBUF_TOKEN || secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository_owner }}/eapp-python-domain/packages \
            -d '{
              "package_type": "pypi",
              "name": "eapp-python-domain"
            }' || echo "Package might already exist"

      - name: Setup GitHub CLI
        run: |
          curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
          sudo apt update
          sudo apt install gh

      - name: Test package upload with environment variables
        env:
          TWINE_USERNAME: ${{ github.actor }}
          TWINE_PASSWORD: ${{ secrets.PROTOBUF_TOKEN || secrets.GITHUB_TOKEN }}
        run: |
          cd eapp-python-domain
          
          echo "Uploading package with environment variables..."
          
          # Use GitHub Packages with the correct URL format
          python -m twine upload --verbose \
            --repository-url https://github.com/${{ github.repository_owner }}/eapp-python-domain/packages/pypi \
            --username ${{ github.actor }} \
            --password ${{ secrets.PROTOBUF_TOKEN || secrets.GITHUB_TOKEN }} \
            dist/*
          
          echo "Upload completed!" 