name: Test Release System

on:
  workflow_dispatch:

jobs:
  test-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Python Domain
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/eapp-python-domain
          token: ${{ secrets.PROTOBUF_TOKEN || secrets.GITHUB_TOKEN }}
          path: eapp-python-domain

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install build setuptools wheel

      - name: Generate test package
        run: |
          cd eapp-python-domain
          
          # Create a unique version based on timestamp
          VERSION="25.7.8.$(date +%s)"
          echo "Using version: $VERSION"
          
          # Create a test package
          echo 'from setuptools import setup, find_packages' > setup.py
          echo 'setup(' >> setup.py
          echo '    name="eapp-python-domain",' >> setup.py
          echo "    version=\"$VERSION\"," >> setup.py
          echo '    description="Test package for GitHub releases",' >> setup.py
          echo '    packages=find_packages(where="src"),' >> setup.py
          echo '    package_dir={"": "src"},' >> setup.py
          echo '    python_requires=">=3.7",' >> setup.py
          echo ')' >> setup.py
          
          # Create source directory
          mkdir -p src/eapp_python_domain
          echo '# Test package' > src/eapp_python_domain/__init__.py
          
          # Show what we're about to build
          echo "Current directory: $(pwd)"
          echo "setup.py contents:"
          cat setup.py
          echo "Directory structure:"
          find . -type f -name "*.py" | head -10
          
          # Build package
          echo "Building package..."
          python -m build
          
          # List what files were created
          echo "Files created in dist/:"
          ls -la dist/ || echo "dist/ directory not found"
          
          # Check if files were created successfully
          TAR_COUNT=$(ls dist/*.tar.gz 2>/dev/null | wc -l)
          WHEEL_COUNT=$(ls dist/*.whl 2>/dev/null | wc -l)
          
          echo "Found $TAR_COUNT tar.gz files and $WHEEL_COUNT wheel files"
          
          if [ "$TAR_COUNT" -eq 0 ]; then
            echo "ERROR: No source distribution (.tar.gz) files found."
            echo "Available files in dist/:"
            ls -la dist/ || echo "dist/ directory is empty or doesn't exist"
            exit 1
          fi
          
          if [ "$WHEEL_COUNT" -eq 0 ]; then
            echo "ERROR: No wheel distribution (.whl) files found."
            echo "Available files in dist/:"
            ls -la dist/ || echo "dist/ directory is empty or doesn't exist"
            exit 1
          fi
          
          echo "✅ Build successful! Found $TAR_COUNT tar.gz files and $WHEEL_COUNT wheel files."
          
          # Store version for later steps
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Create packages directory
        run: |
          cd eapp-python-domain
          mkdir -p packages

      - name: Create package index
        run: |
          cd eapp-python-domain
          
          # Get the actual file names from dist/
          TAR_FILE=$(ls dist/*.tar.gz | head -1)
          WHEEL_FILE=$(ls dist/*.whl | head -1)
          
          echo "Using files: $TAR_FILE and $WHEEL_FILE"
          
          # Sanitize filenames for GitHub (same logic as upload step)
          TAR_BASENAME=$(basename "$TAR_FILE")
          WHEEL_BASENAME=$(basename "$WHEEL_FILE")
          
          # Create simple, safe names: eapp_python_domain-25.7.8.1752925060.tar.gz -> eapp-python-domain-source.tar.gz
          SANITIZED_TAR_NAME="eapp-python-domain-source.tar.gz"
          SANITIZED_WHEEL_NAME="eapp-python-domain-wheel.whl"
          
          echo "Sanitized names for index: $SANITIZED_TAR_NAME and $SANITIZED_WHEEL_NAME"
          
          # Create a simple package index
          echo '<!DOCTYPE html>' > packages/index.html
          echo '<html>' >> packages/index.html
          echo '<head><title>Python Packages</title></head>' >> packages/index.html
          echo '<body>' >> packages/index.html
          echo '<h1>Python Packages</h1>' >> packages/index.html
          echo '<p>Available packages:</p>' >> packages/index.html
          echo '<ul>' >> packages/index.html
          echo "<li><a href=\"https://github.com/50gramx/eapp-python-domain/releases/download/v${{ env.VERSION }}/$SANITIZED_TAR_NAME\">$SANITIZED_TAR_NAME</a></li>" >> packages/index.html
          echo "<li><a href=\"https://github.com/50gramx/eapp-python-domain/releases/download/v${{ env.VERSION }}/$SANITIZED_WHEEL_NAME\">$SANITIZED_WHEEL_NAME</a></li>" >> packages/index.html
          echo '</ul>' >> packages/index.html
          echo '<p>Install with:</p>' >> packages/index.html
          echo '<pre>pip install --index-url https://raw.githubusercontent.com/50gramx/eapp-python-domain/main/packages/index.html eapp-python-domain</pre>' >> packages/index.html
          echo '</body></html>' >> packages/index.html

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PROTOBUF_TOKEN || secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.VERSION }}
          release_name: Release v${{ env.VERSION }}
          body: Test release for package hosting system
          draft: false
          prerelease: false

      - name: Upload package files to release
        run: |
          cd eapp-python-domain
          
          # Get the actual file names
          TAR_FILE=$(ls dist/*.tar.gz | head -1)
          WHEEL_FILE=$(ls dist/*.whl | head -1)
          
          echo "Uploading $TAR_FILE and $WHEEL_FILE"
          
          # Sanitize filenames for GitHub (use simple, safe names)
          TAR_BASENAME=$(basename "$TAR_FILE")
          WHEEL_BASENAME=$(basename "$WHEEL_FILE")
          
          # Create simple, safe names: eapp_python_domain-25.7.8.1752925060.tar.gz -> eapp-python-domain-source.tar.gz
          SANITIZED_TAR_NAME="eapp-python-domain-source.tar.gz"
          SANITIZED_WHEEL_NAME="eapp-python-domain-wheel.whl"
          
          echo "Sanitized names: $SANITIZED_TAR_NAME and $SANITIZED_WHEEL_NAME"
          
          # Upload tar.gz file using multipart form data
          curl -X POST \
            -H "Authorization: token ${{ secrets.PROTOBUF_TOKEN || secrets.GITHUB_TOKEN }}" \
            -F "name=$SANITIZED_TAR_NAME" \
            -F "label=Source Distribution" \
            -F "file=@$TAR_FILE" \
            "${{ steps.create_release.outputs.upload_url }}"
          
          # Upload wheel file using multipart form data
          curl -X POST \
            -H "Authorization: token ${{ secrets.PROTOBUF_TOKEN || secrets.GITHUB_TOKEN }}" \
            -F "name=$SANITIZED_WHEEL_NAME" \
            -F "label=Wheel Distribution" \
            -F "file=@$WHEEL_FILE" \
            "${{ steps.create_release.outputs.upload_url }}"

      - name: Commit and push package index
        run: |
          cd eapp-python-domain
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add packages/
          git commit -m "Add package index for v${{ env.VERSION }}" || echo "No changes to commit"
          git push origin master

      - name: Test completion
        run: |
          echo "Test release system completed!"
          echo "Check: https://github.com/50gramx/eapp-python-domain/releases/tag/v${{ env.VERSION }}"
          echo "Index: https://raw.githubusercontent.com/50gramx/eapp-python-domain/main/packages/index.html" 