name: Test Release System

on:
  workflow_dispatch:

jobs:
  test-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Python Domain
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/eapp-python-domain
          token: ${{ secrets.PROTOBUF_TOKEN || secrets.GITHUB_TOKEN }}
          path: eapp-python-domain

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install build setuptools wheel

      - name: Generate test package
        run: |
          cd eapp-python-domain
          
          # Create a test package
          echo 'from setuptools import setup, find_packages' > setup.py
          echo 'setup(' >> setup.py
          echo '    name="eapp-python-domain",' >> setup.py
          echo '    version="25.7.8",' >> setup.py
          echo '    description="Test package for GitHub releases",' >> setup.py
          echo '    packages=find_packages(where="src"),' >> setup.py
          echo '    package_dir={"": "src"},' >> setup.py
          echo '    python_requires=">=3.7",' >> setup.py
          echo ')' >> setup.py
          
          # Create source directory
          mkdir -p src/eapp_python_domain
          echo '# Test package' > src/eapp_python_domain/__init__.py
          
          # Build package
          python -m build

      - name: Create packages directory
        run: |
          cd eapp-python-domain
          mkdir -p packages

      - name: Create package index
        run: |
          cd eapp-python-domain
          
          # Create a simple package index
          echo '<!DOCTYPE html>' > packages/index.html
          echo '<html>' >> packages/index.html
          echo '<head><title>Python Packages</title></head>' >> packages/index.html
          echo '<body>' >> packages/index.html
          echo '<h1>Python Packages</h1>' >> packages/index.html
          echo '<p>Available packages:</p>' >> packages/index.html
          echo '<ul>' >> packages/index.html
          echo '<li><a href="https://github.com/50gramx/eapp-python-domain/releases/download/v25.7.8/eapp-python-domain-25.7.8.tar.gz">eapp-python-domain-25.7.8.tar.gz</a></li>' >> packages/index.html
          echo '</ul>' >> packages/index.html
          echo '<p>Install with:</p>' >> packages/index.html
          echo '<pre>pip install --index-url https://raw.githubusercontent.com/50gramx/eapp-python-domain/main/packages/index.html eapp-python-domain</pre>' >> packages/index.html
          echo '</body></html>' >> packages/index.html

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PROTOBUF_TOKEN || secrets.GITHUB_TOKEN }}
        with:
          tag_name: v25.7.8
          release_name: Release v25.7.8
          body: Test release for package hosting system
          draft: false
          prerelease: false

      - name: Upload package files to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PROTOBUF_TOKEN || secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./eapp-python-domain/dist/eapp-python-domain-25.7.8.tar.gz
          asset_name: eapp-python-domain-25.7.8.tar.gz
          asset_content_type: application/gzip

      - name: Commit and push package index
        run: |
          cd eapp-python-domain
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add packages/
          git commit -m "Add package index for v25.7.8" || echo "No changes to commit"
          git push origin master

      - name: Test completion
        run: |
          echo "Test release system completed!"
          echo "Check: https://github.com/50gramx/eapp-python-domain/releases/tag/v25.7.8"
          echo "Index: https://raw.githubusercontent.com/50gramx/eapp-python-domain/main/packages/index.html" 