name: Test Simple Workflow

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  test-basic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test basic functionality
        run: |
          echo "Testing basic workflow functionality..."
          echo "Repository: ${{ github.repository }}"
          echo "Branch: ${{ github.ref }}"
          echo "Workspace: ${{ github.workspace }}"
          
          # Check if protobuf files exist
          if [ -d "src/main/proto" ]; then
            echo "✅ Proto directory exists"
            ls -la src/main/proto/
          else
            echo "❌ Proto directory not found"
            echo "Current directory contents:"
            ls -la
          fi
          
          # Test repository access
          echo "Testing repository access..."
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
               https://api.github.com/repos/${{ github.repository_owner }}/eapp-python-domain \
               | jq '.name' || echo "❌ Cannot access eapp-python-domain repository"

  test-repository-access:
    runs-on: ubuntu-latest
    steps:
      - name: Test repository access
        run: |
          echo "Testing access to domain repositories..."
          
          REPOS=("eapp-python-domain" "eapp-nodejs-domain" "eapp-dart-domain" "eapp-kotlin-domain" "eapp-swift-domain")
          
          for repo in "${REPOS[@]}"; do
            echo "Checking $repo..."
            response=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                           https://api.github.com/repos/${{ github.repository_owner }}/$repo)
            
            if echo "$response" | jq -e '.name' > /dev/null 2>&1; then
              echo "✅ $repo exists and is accessible"
            else
              echo "❌ $repo not found or not accessible"
              echo "Response: $response"
            fi
          done 